CREATE TABLE IF NOT EXISTS cabang (
    id_cabang INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    lokasi VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
    id_role INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_role VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT ck_roles_nama_role_allowed
        CHECK (nama_role IN ('user', 'admin', 'owner'))
);

CREATE TABLE IF NOT EXISTS users (
    id_user INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    no_hp VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS tempat (
    id_tempat INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cabang INTEGER NOT NULL,
    nomor_meja VARCHAR(50) NOT NULL,
    harga NUMERIC(12, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_tempat_cabang
        FOREIGN KEY (id_cabang)
        REFERENCES cabang (id_cabang)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS permissions (
    id_permission INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_role INTEGER NOT NULL,
    nama_permission VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT fk_permissions_role
        FOREIGN KEY (id_role)
        REFERENCES roles (id_role)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_roles (
    id_user INTEGER NOT NULL,
    id_role INTEGER NOT NULL,
    PRIMARY KEY (id_user, id_role),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (id_user)
        REFERENCES users (id_user)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (id_role)
        REFERENCES roles (id_role)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS jadwal (
    id_jadwal INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tempat INTEGER NOT NULL,
    tanggal DATE NOT NULL,
    jam_mulai TIME NOT NULL,
    jam_selesai TIME NOT NULL,
    CONSTRAINT fk_jadwal_tempat
        FOREIGN KEY (id_tempat)
        REFERENCES tempat (id_tempat)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS laporan (
    id_laporan INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipe VARCHAR(100) NOT NULL,
    lampiran VARCHAR(255) NOT NULL,
    dibuat_oleh INTEGER NOT NULL,
    CONSTRAINT fk_laporan_user
        FOREIGN KEY (dibuat_oleh)
        REFERENCES users (id_user)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reservasi (
    id_reservasi INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user INTEGER NOT NULL,
    id_jadwal INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,
    total_harga NUMERIC(12, 2) NOT NULL,
    CONSTRAINT fk_reservasi_user
        FOREIGN KEY (id_user)
        REFERENCES users (id_user)
        ON DELETE CASCADE,
    CONSTRAINT fk_reservasi_jadwal
        FOREIGN KEY (id_jadwal)
        REFERENCES jadwal (id_jadwal)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments (
    id_payment INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reservasi INTEGER NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_payments_reservasi
        FOREIGN KEY (id_reservasi)
        REFERENCES reservasi (id_reservasi)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payment_logs (
    id_log INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_payment INTEGER NOT NULL,
    response TEXT NOT NULL,
    CONSTRAINT fk_payment_logs_payment
        FOREIGN KEY (id_payment)
        REFERENCES payments (id_payment)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS refunds (
    id_refund INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_payment INTEGER NOT NULL,
    amount NUMERIC(12, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_refunds_payment
        FOREIGN KEY (id_payment)
        REFERENCES payments (id_payment)
        ON DELETE CASCADE
);
